### ISSUE TITLE
Test case while-do-error-004

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qt4tests#103]
I think this test case isn't obliged to report a type error.

```
<test-case name="while-do-error-004" covers-40="PR828">
    <description>Wrong action type</description>
    <created by="Christian Gruen" on="2023-11-18"/>
    <test><![CDATA[
head(while-do(
  (1, 2),
  fn($x, $p) { $p < 2 },
  fn($s, $p as xs:string) { $s[2], $s[1] }
))]]></test>
    <result>
      <error code="XPTY0004"/>
    </result>
  </test-case>
```

I don't think there is any rule that requires you to check whether an argument to a function has the correct type if the argument is never used.

And a processor certainly isn't required to any static type analysis to establish that the argument types xs:string and xs:integer are disjoint.

§2.4.4 Errors and Optimization applies: _Another consequence of these rules is that where none of the items in a sequence contributes to the result of an expression, the processor is not obliged to evaluate any part of the sequence._

**Comment by ChristianGruen** [comment]
True, thanks. I hope the version in the PR matches the requirements.
