### ISSUE TITLE
Test case fn-parse-json-736

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qt4tests#114]
The test does

```
<test-case name="fn-parse-json-736" covers-40="PR975">
      <description>fallback option yielding an empty sequence</description>
      <created by="Christian Gruen" on="2024-03-14"/>
      <dependency type="spec" value="XP40+ XQ40+"></dependency>
      <test>parse-json('"a\bc"', map { 'fallback': void#1 })</test>
      <result>
         <assert-string-value>ac</assert-string-value>
      </result>
 </test-case>
```

The type of the fallback function is defined as `function(xs:string) as xs:anyAtomicType`, which does not allow an empty sequence as the result, so I think the test should fail XPTY0004.

(Frankly, it's not clear to me why we allow the fallback function to return any atomic type, which then gets cast to a string.)

**Comment by ChristianGruen** [comment]
Thanks.

> (Frankly, it's not clear to me why we allow the fallback function to return any atomic type, which then gets cast to a string.)

The motivation was similar as for the `$action` parameter of `fn:replace`: It allows users to return arbitrary atomic items (numbers, booleans, etc.) without the need to explicitly cast them to strings.
