### ISSUE TITLE
map:of-pairs atomization

### ISSUE THREAD

**Issue by michaelhkay** [qt4cg/qt4tests#124]
Tests map-of-pairs-905/906 test that the keys in the key-value-pairs supplied to map:of-pairs are not atomized.

I believe this is incorrect. The function signature declares the input argument as being of type

`$input as record(key as xs:anyAtomicType, value as item()*)*`

which I think should lead to atomization of the keys.

**Comment by ChristianGruen** [comment]
Fixed (https://github.com/qt4cg/qt4tests/commit/4451f06b72e55f2aab0c9686200c2f7145149bd8).
