### ISSUE TITLE
Item coercion from xs:anyURI to enum?

### ISSUE THREAD

**Issue by GuntherRademacher** [qt4cg/qt4tests#135]
I have doubts about the expected result of test case `DynamicFunctionCall-136`:

```xml
<test-case name="DynamicFunctionCall-136">
  <description>Promotion for enumeration types</description>
  <created by="Michael Kay" on="2024-02-09"/>
  <modified by="Michael Kay" on="2024-04-18" change="new rules say promotion happens here"/>
  <test>
	 let $f := function($in as enum("a", "b", "c")) as xs:string {
		string($in)
	 }
	 return $f(xs:anyURI('a'))</test>
  <result>
	 <assert-string-value>a</assert-string-value>
  </result>
</test-case>
```

For creating the expected result, it would be necessary to coerce from `xs:anyURI('a')` to `enum("a", "b", "c")`, but I cannot see how this is covered by the spec. 

My understanding is that it takes casting to go from `xs:anyURI` to `xs:string`, but as an `xs:string` is not an instance of an enumeration, it also takes relabeling to get there. However as I read the spec, casting and relabeling are not combinable. Thus I would expect the test case to result in `XPTY0004`.

What am I missing here?

**Comment by michaelhkay** [comment]
Yes, I think you are right.

**Comment by GuntherRademacher** [comment]
Added #136 to fix this.
