### ISSUE TITLE
compareTypes.xquery: Variable Declaration

### ISSUE THREAD

**Issue by ChristianGruen** [qt4cg/qt4tests#189]
@michaelhkay I believe the XQuery code for the subtyping tests needs to be fixed:

https://github.com/qt4cg/qt4tests/blob/master/misc/Subtyping/compareTypes.xquery

I think it is legal for an implementation to raise an error for…

```xquery
declare variable $cmp:var as item()* external := '';

declare function cmp:compareTypes() as xs:boolean {
  (function() as %TYPE0% {$cmp:var} instance of function() as %TYPE1%)
};
```

…if it is known that the predeclared value `''` will not be overwritten by an external value.

What was the reason in the first place to bind the value to an external variable if it is never changed by the tests?

**Comment by michaelhkay** [comment]
Well, I think the reasoning is that a processor cannot possibly know at compile time what the run-time value of the variable will be. That's perhaps based on a rather strict interpretation of the processing model, which says that static errors can only be raised during the static analysis phase, and that the static analysis phase works with no knowledge of input data.

If you can think of a better way to avoid spurious static errors here, by all means suggest it.
