### ISSUE TITLE
HtmlTestSuite - expected results have SVG elements in lower case

### ISSUE THREAD

**Issue by GuntherRademacher** [qt4cg/qt4tests#57]
There are at least 20 tests in the HtmlTestSuite that expect the following SVG element names in lower case, where the SVG schema specifies camel case:

- clipPath
- feColorMatrix
- feComponentTransfer
- feComposite
- feDiffuseLighting
- feFlood
- feGaussianBlur
- feOffset
- feTurbulence
- foreignObject
- linearGradient

The tests are:

- [0011](https://github.com/qt4cg/qt4tests/blob/master/misc/HtmlTestSuite/results/test-0011.xhtml)
- [0022](https://github.com/qt4cg/qt4tests/blob/master/misc/HtmlTestSuite/results/test-0022.xhtml)
- [0048](https://github.com/qt4cg/qt4tests/blob/master/misc/HtmlTestSuite/results/test-0048.xhtml)
- [0458](https://github.com/qt4cg/qt4tests/blob/master/misc/HtmlTestSuite/results/test-0458.xhtml)
- [0463](https://github.com/qt4cg/qt4tests/blob/master/misc/HtmlTestSuite/results/test-0463.xhtml)
- [0464](https://github.com/qt4cg/qt4tests/blob/master/misc/HtmlTestSuite/results/test-0464.xhtml)
- [0466](https://github.com/qt4cg/qt4tests/blob/master/misc/HtmlTestSuite/results/test-0466.xhtml)
- [0467](https://github.com/qt4cg/qt4tests/blob/master/misc/HtmlTestSuite/results/test-0467.xhtml)
- [0614](https://github.com/qt4cg/qt4tests/blob/master/misc/HtmlTestSuite/results/test-0614.xhtml)
- [0615](https://github.com/qt4cg/qt4tests/blob/master/misc/HtmlTestSuite/results/test-0615.xhtml)
- [0617](https://github.com/qt4cg/qt4tests/blob/master/misc/HtmlTestSuite/results/test-0617.xhtml)
- [0619](https://github.com/qt4cg/qt4tests/blob/master/misc/HtmlTestSuite/results/test-0619.xhtml)
- [0621](https://github.com/qt4cg/qt4tests/blob/master/misc/HtmlTestSuite/results/test-0621.xhtml)
- [0623](https://github.com/qt4cg/qt4tests/blob/master/misc/HtmlTestSuite/results/test-0623.xhtml)
- [0625](https://github.com/qt4cg/qt4tests/blob/master/misc/HtmlTestSuite/results/test-0625.xhtml)
- [0626](https://github.com/qt4cg/qt4tests/blob/master/misc/HtmlTestSuite/results/test-0626.xhtml)
- [0628](https://github.com/qt4cg/qt4tests/blob/master/misc/HtmlTestSuite/results/test-0628.xhtml)
- [0629](https://github.com/qt4cg/qt4tests/blob/master/misc/HtmlTestSuite/results/test-0629.xhtml)
- [0758](https://github.com/qt4cg/qt4tests/blob/master/misc/HtmlTestSuite/results/test-0758.xhtml)
- [1024](https://github.com/qt4cg/qt4tests/blob/master/misc/HtmlTestSuite/results/test-1024.xhtml)

In all cases where I have looked up the input files for those tests, I found the camel case spelling there. But nu.validator would return the camel case version, even if the input had different casing.

Am I missing something here, or are the expected results indeed wrong to this respect? In this case I would be happy to send a PR correcting the casing for those elements.

**Comment by michaelhkay** [comment]
For info, with Saxon we're currently failing the following tests in SaxonJ (which uses validator.nu):

```
     html-test-1050
      html-test-1054
      html-test-1147
      html-test-1216
      html-test-1238
      html-test-1258
      html-test-1294
      html-test-1296
```
and the following in SaxonCS (which uses AngleSharp):

```
     html-test-0011
      html-test-0033
      html-test-0061
      html-test-0081
      html-test-0186
      html-test-0189
      html-test-0190
      html-test-0191
      html-test-0211
      html-test-0395
      html-test-0443
      html-test-0467
      html-test-0519
      html-test-0611
      html-test-0638
      html-test-0758
      html-test-0965
      html-test-0966
      html-test-1018
      html-test-1024
      html-test-1050
      html-test-1054
      html-test-1101
      html-test-1147
      html-test-1167
      html-test-1216
      html-test-1238
      html-test-1258
      html-test-1357
      html-test-1358
      html-test-1362
      html-test-1363
      html-test-1368
```

Not much overlap between these lists, unfortunately.

The test suite references a file tools/readme.md which should be tools/_readme.md -- this explains how the test data was generated. Essentially I think the reference results were produced by Soup; it does look as if one or two of them have been hand-modified. It would be good to preserve the ability to regenerate the tests, perhaps taking a larger sample of the original HTML test suite. To that end, if we're going to produce hand-corrected result files, it might be an idea to put them in a separate directory, so the test comparison logic can compare first against the hand-corrected result if it exists, then against the auto-generated result otherwise.

I've looked at 0011 and confirm that SaxonJ (using validator.nu) is generating the SVG element name in lower case. I don't have a clean SaxonCS handy to see what that is doing.

**Comment by michaelhkay** [comment]
Confirmed that SaxonCS (using AngleSharp) is also outputting SVG element names in lower case.

So, what exactly does the spec say? Actually (as I think I have commented before) it's somewhat deficient in that it doesn't actually say what the function does; it just provides a lot of notes about how it does it.

However, §15.6.10 says _The Element.localName property will be ASCII lowercase._ 

And I don't see any statement that any SVG elements will conform with the SVG schema; though it's certainly a bit unfortunate if they don't. I'll raise a spec issue.

**Comment by michaelhkay** [comment]
I have raised a spec issue at https://github.com/qt4cg/qtspecs/issues/767. For the moment, I think the tests are correct (but others may differ!)

**Comment by GuntherRademacher** [comment]
Thank you for looking into this. I presume that SaxonJ is forcing SVG element names to lower case, since Validator.nu outputs the spelling per the SVG schema.

I have also checked `results/test-0011.xhtml` with Firefox, Chrome, and Opera, and all of them will render it in the same way as `files/test-0011.html` if and only if

- the foreignObject element name is in camel case, and
- the div child of foreignObject is in the xhtml namespace.

Both of this is guaranteed by Nu.validator, but differs from the test cases' expectations.

**Comment by michaelhkay** [comment]
Yes, you're right, it seems Saxon is forcing the element names to lower case.

**Comment by ChristianGruen** [comment]
> Yes, you're right, it seems Saxon is forcing the element names to lower case.

Good to know. Maybe we should report those cases back to the developers of validator.nu. Have you added some more tweaks to get the results right?

**Comment by gsnedders** [comment]
> However, §15.6.10 says _The Element.localName property will be ASCII lowercase._

https://qt4cg.org/specifications/xpath-functions-40/Overview.html#html-node-name-accessor presumably? That seems to be an informative note; the normative text seems correct (which doesn't require or perform any case conversion).

https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inforeign in HTML tree construction adjusts elements to have the right local name and attributes the right namespace and local name, thus the test suite is wrong.

**Comment by ndw** [comment]
FYI, I did ping Henry Sivonen on Mastodon to see if he wanted to make any comments on this issue. (He's the author of the validator.nu library.)

**Comment by rhdunn** [comment]
Digging through the HTML5 specs, https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inforeign has the following:
> If the [adjusted current node](https://html.spec.whatwg.org/multipage/parsing.html#adjusted-current-node) is an element in the [SVG namespace](https://infra.spec.whatwg.org/#svg-namespace), and the token's tag name is one of the ones in the first column of the following table, change the tag name to the name given in the corresponding cell in the second column. (This fixes the case of SVG elements that are not all lowercase.)

This then lists tag names such as `foreignobject` mapping to the correct element name (`foreignObject` in this case).

Thus, in the HTMLDocument parsed DOM, the tag name is case insensitive, but the corresponding element name for SVG is not!

**Comment by rhdunn** [comment]
I'll need to check what the HTMLDocument representation of these looks like in browsers to verify if the XDM conversion needs updating with that mapping for local names, or if a note is sufficient.

**Comment by gsnedders** [comment]
> Thus, in the HTMLDocument parsed DOM, the tag name is case insensitive, but the corresponding element name for SVG is not!

Searching for "HTML Document" in the [DOM spec](https://dom.spec.whatwg.org/) may be illuminating; a lot of the old (non-namespace-aware) APIs do case-conversion, but then the namespace-aware APIs do not. Essentially the DOM tree should be case-sensitive, even if the parser and APIs do case conversion to make that possible.

For example, in an HTML document `document.createElement("A")` will create a `("http://www.w3.org/1999/xhtml", "a")`, but `document.createElementNS("http://www.w3.org/1999/xhtml", "A")` will create a `("http://www.w3.org/1999/xhtml", "A")` (and that's an unknown element in the HTML namespace—and [browsers do nothing with it](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cbody%3E%0A%3Cscript%3E%0Adocument.body.appendChild(document.createElementNS(%22http%3A%2F%2Fwww.w3.org%2F1999%2Fxhtml%22%2C%20%22A%22))%3B%0Adocument.body.lastChild.textContent%20%3D%20%22test%22%3B%0Adocument.body.lastChild.setAttribute(%22href%22%2C%20%22http%3A%2F%2Fexample.com%22)%3B%0A%3C%2Fscript%3E), with it not acting like an anchor).

I would _expect_ you should just be defining the conversion to XDM based on the namespace-aware APIs, which means you preserve the case the DOM already has, which IIRC the specs already do.

**Comment by rhdunn** [comment]
@gsnedders Thanks! Testing with `data:text/html,<html><svg><foreignobject>` and inspecting the DOM properties, both Firefox and Edge set the `Node.localName` property to the case-sensitive name. As such, the https://qt4cg.org/specifications/xpath-functions-40/Overview.html#html-node-name-accessor rules don't need to change, although I can add a note to document this quirk in the HTML spec behaviour.

**Comment by michaelhkay** [comment]
>I would expect you should just be defining the conversion to XDM based on the namespace-aware APIs

I'm not sure that's right. We're not concerned with a DOM that's created using Javascript APIs, we're only concerned with a DOM that's produced from lexical HTML by the HTML5 parsing algorithm.

**Comment by rhdunn** [comment]
@michaelhkay The HTML parsing algorithm -- specifically the tree construction step -- constructs a HTML DOM tree. Javascript has a binding to that DOM tree. The HTML to XDM mapping specification defines the conversion in terms of the constructed tree, i.e. the resulting DOM tree from the parser.

The spec is written in such a way that if the parser has a different API, or exposes the equivalent DOM tree methods to a different language, as long as the mapping is equivalent to using the specified DOM APIs then it is conforming.

**Comment by gsnedders** [comment]
> > I would expect you should just be defining the conversion to XDM based on the namespace-aware APIs
> 
> I'm not sure that's right. We're not concerned with a DOM that's created using Javascript APIs, we're only concerned with a DOM that's produced from lexical HTML by the HTML5 parsing algorithm.

Sure, but as currently defined the spec says things like "The local name is the value of the `Element.localName` property", which very much seems like defining it in terms of the namespace-aware APIs.

Certainly you could avoid this with something like, "the local name is the [local name](https://dom.spec.whatwg.org/#concept-element-local-name) of node", though that is practically equivalent (at least in this case—the localNode attribute on Element is just a getter for its local name), at least in this case (but might be slightly better specification practice, unless the behaviour of the IDL operations/attributes is in any way relevant).

**Comment by michaelhkay** [comment]
Misunderstanding here, I think. @gsnedders was referring to DOM construction APIs like `createElementNS()`. I don't think those are relevant to us. But defining how we convert the DOM to an XDM by reference to DOM accessor methods is fine.

**Comment by hsivonen** [comment]
> FYI, I did ping Henri Sivonen on Mastodon to see if he wanted to make any comments on this issue. (He's the author of the validator.nu library.)

Sorry about the delay. (Busy week.)

What @gsnedders says is correct.

My summary of the situation:

1. The HTML tokenizer ASCII-lower-cases everything, but then the tree builder has a hard-coded list of SVG camelCase name adjustments so that the `localName` that ends up in the DOM is the SVG camelCased name.
2. Operations on the DOM should be written to the namespace-aware Level 2 view, in which case the same code works for both HTML parser-created and XML parser-created DOM trees.
3. The HTMLness bit on the DOM document affects the behavior of Level 1 APIs: It makes `tagName` return an ASCII-uppercased value for elements in the HTML namespace.
4. The informative note "The `Element.localName` property will be ASCII lowercase." in the XPath 4.0 spec draft is incorrect for elements in the SVG namespace.

**Comment by michaelhkay** [comment]
I have fixed these tests (and am in the process of fixing Saxon to pass them)
