### ISSUE TITLE
fn:format-integer - fall back strategy on ICU rule set name mismatch

### ISSUE THREAD

**Issue by GuntherRademacher** [qt4cg/qt4tests#66]
While working on test cases for fn:format-integer, I came across [`format-integer-077`](https://github.com/qt4cg/qt4tests/blob/3392bd4e821b8434b2ff238004ddf6eb04ace891/fn/format-integer.xml#L748-L760), and I am in doubt about the expected result. This is what the test case looks like:

```xml
<test-case name="format-integer-077">
    <description>format-integer - Cardinal number output request - German - using CLDR</description>
    <created by="Michael Kay" on="2022-12-02"/>
    <dependency type="language" value="de"/>
    <dependency type="feature" value="fn-format-integer-CLDR"/>
    <test>format-integer(1, 'Ww;c(%spellout-ordinal-feminine)', 'de'),
        format-integer(1, 'Ww;c(%spellout-ordinal-s)', 'de'),
        format-integer(1, 'Ww;c(%spellout-ordinal-r)', 'de'),
        format-integer(1, 'Ww;c(%spellout-ordinal-n)', 'de')</test>
    <result>
        <assert-deep-eq>"Ein", "Erstes", "Erster", "Ersten"</assert-deep-eq>
    </result>    
</test-case>
```

Note 3 of [4.6.1. fn:format-integer](https://www.w3.org/TR/xpath-functions-31/#func-format-integer) suggests that ICU might be used, which obviously is assumed by this test case. Given that, the invocations of the function have contradictory modifiers, specifying

   - cardinal numbering as indicated by `c`,
   - ordinal numbering as indicated by `%spellout-ordinal-*` ICU rule set names.
   
The first invocation of the function asks for ICU rule set `%spellout-ordinal-feminine`. However ICU does not have that available for locale `de`, so an implementation has to apply some fallback strategy. But

   - the default rule set for `de` is `%spellout-numbering`, but this is not expected to be used,
   - the asked-for rule set has `%spellout-ordinal*`, and `de` provides `%spellout-ordinal`, but that is not expected to be used,
   - the asked-for rule set has `*-feminine` and `de` provides `%spellout-cardinal-feminine`, but that is not expected to be used,
   - rather the test case expects using either of `%spellout-cardinal-masculine` or `%spellout-cardinal-neuter`, which can be seen from the fact that these are the only `de` rule sets that produce the result `Ein`. The more generic `%spellout-cardinal` is supported for other languages, but not for `de`.
   
Apparently the expectation is that the rule set name is ignored in case it cannot be matched exactly, then resorting to the `c` specification. This surely is a valid approach.

But could not a fallback strategy also try to resolve the mismatch with supported rule sets first? I would argue that the supported `%spellout-ordinal` is more generic than  `%spellout-ordinal-feminine`, so it could well be seen as a valid fallback. It would produce `Erste`, which is perfectly valid for the feminine case of ordinal numbering.

My question is, isn't this test case too ambitious? It assumes a specific fallback strategy, which I could not align with any specification yet. The interpretation of the parenthesized content of the format modifier is implementation-defined, after all.

While I fully agree that it is a good idea to use ICU, I can't see yet that there is only one obvious choice for falling back in cases like this.

**Comment by michaelhkay** [comment]
You're probably right that this test case is over-ambitious, and it should have been added to our private version of the test suite. However, we've always found it very useful to see "challenging" test cases submitted by other implementors, and if we decide that they make assumptions that can't be justified from the spec, then we either propose alternative results, or simply add the test to our exceptions list.

I need to explore how this relates to https://saxonica.plan.io/issues/5792 which also discusses fallbacks for ICU numbering schemes.
